name: simulation
root: ./
startup_window: status
pre_window: export UAV_NAME=uav1;
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - rviz:
      layout: tiled
      panes:
        - waitForRos; rviz -d $(rospack find mrs_serial)/rviz/gimbal.rviz
        - waitForRos; rosrun rqt_reconfigure rqt_reconfigure
  - gimbal:
      layout: tiled
      panes:
        -  waitForRos; roslaunch mrs_serial gimbal.launch

